# Generated by Django 2.0.6 on 2020-03-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=5)),
                ('create_time', models.DateField()),
                ('province', models.CharField(max_length=32)),
                ('addr', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=32)),
                ('status', models.IntegerField()),
                ('pic', models.ImageField(upload_to='user_pic')),
                ('sinature', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
